version: "3"


services:
#  application:
#    build:
#      context: .
#      dockerfile: .docker/application-dev.Dockerfile
#    environment:
#      APPLICATION_PORT: "8080"
#    ports:
#    - 8080:8080
#    volumes:
#    - ./src:/home/node/app/src

  components:
    build:
      context: .
      dockerfile: .docker/components-dev.Dockerfile
    environment:
      COMPONENTS_PORT: "8081"
    ports:
    - 8081:8081
    volumes:
    - ./components:/home/node/app/components

  storybook:
    build:
      context: .
      dockerfile: .docker/storybook-dev.Dockerfile
    environment:
      STORYBOOK_PORT: "8082"
    ports:
    - 8082:8082
    volumes:
    - ./.storybook:/home/node/app/.storybook
    - ./components:/home/node/app/components
    - ./stories:/home/node/app/stories